# Generated by Django 5.2.7 on 2025-11-15 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('tipo_reporte', models.CharField(choices=[('notas_estudiante', 'Notas por Estudiante'), ('notas_asignatura', 'Notas por Asignatura'), ('resumen_general', 'Resumen General'), ('estudiantes_riesgo', 'Estudiantes en Riesgo')], max_length=20)),
                ('semestre', models.CharField(blank=True, max_length=10, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('estado_academico', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('suspendido', 'Suspendido')], max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.curso')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Académico',
                'verbose_name_plural': 'Reportes Académicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=20)),
                ('filtros_aplicados', models.TextField()),
                ('formato_exportacion', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.reporteacademico')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
